#ifndef _DS_ERROR_H
#define _DS_ERROR_H

enum {
    RET_OK = 0,
    RET_FAILED =1,
    RET_E_INVALID_PARAM =2,
    RET_E_MODULE_UNINITED =3,
    RET_E_MODULE_INIT_FAILED =4,
    RET_E_INVALID_PORT =5,
    RET_E_INVALID_APP_MESSAGE =6,
    RET_E_ILLEGAL_APP_MESSAGE_FORMAT = 7,
    RET_E_APP_MESSAGE_NO_FREE = 8,
    RET_E_INVALID_DOC_TRANS_TYPE = 9,
    RET_E_DOC_TRANS_TASK_EXITSTED = 10,
    RET_E_INVALID_DOC_MESSAGE =11,
    RET_E_ILLEGAL_TS_MESSAGE_FORMAT =12,
    RET_E_TS_USED_UP =13, //For ts
    RET_E_TS_RESPONSE_FAILED =14, //For ts
    RET_E_IVALID_TS_RESPONSE_MESSAGE =15,
    RET_E_IVALID_TS_RESULT_MESSAGE =16,
    RET_E_IVALID_TS_DISPOSE_RESULT =17,
    RET_E_REPEATED_TS_TRANS_TASK =18,
    RET_E_DOCUMENT_NOT_EXIST = 19,
    RET_E_TASK_PATH_FAILED = 20,
    RET_E_PDF_TO_SWF_FAILED = 21,
    RET_E_GIF_TO_SWF_FAILED = 22,
    RET_E_PNG_TO_SWF_FAILED = 23,
    RET_E_JPG_TO_SWF_FAILED = 24,
    RET_E_OFFICE_TO_PDF_FAILED = 25,
    RET_E_GET_LIB_PATH_FAILED = 26,
    RET_E_REPEATED_TS_ID = 27,
    RET_E_TELNET_PARAM_ERROR =28,
    RET_E_TELNET_NOT_CONNECT =29,
    RET_E_TELNET_SOCK_ERROR =30,
    RET_E_TELNET_SEND_OVERFLOW =31,
    RET_E_TELNET_BIND_FAIL = 32,
    RET_E_TELNET_SEM_FAIL =33,
    RET_E_TELNET_TASK_FAIL =34,
    RET_E_TELNET_SERVER_FAIL = 35,
    RET_E_TELNET_LISTEN_FAIL =36,
    RET_E_EXCUTE_TASK_TIMEOUT =37
};

#endif//_DS_ERROR_H

